name: enum_plus
description: Simple, extensible and powerful enumeration implementation
version: 1.0.0
homepage: https://github.com/aydinfatih/enum_plus
repository: https://github.com/aydinfatih/enum_plus

environment:
  sdk: '>=2.17.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
